modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="firework_table"
version="${version}"
displayName="Firework Table"
authors="Sir Squidly"
description='''Adds a utility block to simplify crafting firework stars.'''
[[dependencies.firework_table]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"
[[dependencies.firework_table]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
