architectury { platformSetupLoomIde(); fabric() }
sourceSets.main.java.srcDir project(':common').file('src/main/java')
sourceSets.main.resources.srcDir project(':common').file('src/main/resources')

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    modImplementation "dev.architectury:architectury-fabric:${rootProject.architectury_api_version}"
}

processResources {
    inputs.property 'version', rootProject.mod_version
    filesMatching('fabric.mod.json') { expand 'version': rootProject.mod_version }
}
