org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

minecraft_version=1.21.1
enabled_platforms=fabric,neoforge
architectury_api_version=13.0.8
mod_version=1.0.1.1
maven_group=com.sirsquidly.firework_table
archives_base_name=firework_table
mod_id=firework_table

fabric_loader_version=0.16.10
fabric_api_version=0.107.0+1.21.1
neoforge_version=21.1.80
