modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"
[[mods]]
modId="firework_table"
version="${version}"
displayName="Firework Table"
authors="Sir Squidly"
description='''Adds a utility block to simplify crafting firework stars.'''
[[dependencies.firework_table]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.firework_table]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
