architectury { platformSetupLoomIde(); neoForge() }

base { archivesName = "${rootProject.archives_base_name}-neoforge" }

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

sourceSets.main.java.srcDir project(':common').file('src/main/java')
sourceSets.main.resources.srcDir project(':common').file('src/main/resources')

repositories {
    maven { url = 'https://maven.architectury.dev/' }
    maven { url = 'https://maven.neoforged.net/releases/' }
}

dependencies {
    neoForge "net.neoforged:neoforge:${rootProject.neoforge_version}"
    implementation "dev.architectury:architectury-neoforge:${rootProject.architectury_api_version}"
}

processResources {
    inputs.property 'version', rootProject.mod_version
    filesMatching('META-INF/neoforge.mods.toml') { expand 'version': rootProject.mod_version }
}
